preshow:
  ip: 10.8.1.21
adminStructure:
  ip: 10.8.1.21
army:
  ip: 10.8.3.21
tradPath:
  ip: 10.8.4.21
christians:
  pj_1: 10.8.5.21
  pj_2: 10.8.5.22
radzivilProjectors:
  pj_1: 10.8.7.21
  pj_2: 10.8.7.22
gaziboProjector:
  pj_1: 10.8.8.21
dayToDay:
  pj_1: 10.8.9.21
heritage:
  pj_1: 10.8.9.21
vladimirBook:
  pj_1: 10.8.12.21
