preshow:
  ip: 10.8.1.11
  mac: CC:28:AA:D0:38:D0
adminStructure:
  ip: 10.8.2.12
  mac: 34:5A:60:E8:1E:DA
molivduls:
  ip: 10.8.2.11
  mac: 34:5A:60:E8:1E:DD
army:
  ip: 10.8.3.11
  mac: 34:5A:60:E8:1E:D9
tradPath:
  ip: 10.8.4.11
  mac: A0:AD:9F:D1:CB:9B
christians:
  ip: 10.8.5.11
  mac: 34:5A:60:E8:1F:05
bishops:
  ip: 10.8.5.12
  mac: A0:AD:9F:D4:C3:18
chirchStaff:
  ip: 10.8.5.13
  mac: A0:AD:9F:D4:C2:9B
arc:
  ip: 10.8.6.11
  mac: A0:AD:9F:D3:16:DF
pilgrimage:
  ip: 10.8.7.12
  mac: A0:AD:9F:D1:CB:63
radzivilProjectors:
  ip: 10.8.7.11
  mac: A0:AD:9F:D4:C3:4C
radzivilTouch:
  ip: 10.8.7.13
  mac: A0:AD:9F:D4:C4:5E
gaziboTouch1:
  ip: 10.8.8.11
  mac: 34:5A:60:E8:1F:0A
gaziboTouch2:
  ip: 10.8.8.12
  mac: A0:AD:9F:D4:C3:90
gaziboTouch3:
  ip: 10.8.8.13
  mac: A0:AD:9F:D4:C3:91
gaziboTouch4:
  ip: 10.8.8.14
  mac: A0:AD:9F:D4:C3:92
gaziboProjector:
  ip: 10.8.8.15
  mac: A0:AD:9F:D4:C3:91
dayToDay:
  ip: 10.8.9.11
  mac: A0:AD:9F:D4:C4:13
agroCulture:
  ip: 10.8.10.11
  mac: A0:AD:9F:D1:CB:8C
heritage:
  ip: 10.8.11.11
  mac: 34:5A:60:E8:1E:DF
vladimirBook:
  ip: 10.8.12.11
  mac: A0:AD:9F:D4:C4:61
lastDecades:
  ip: 10.8.12.12
  mac: 34:5A:60:E8:1F:0F
bizantineSound:
  ip: 10.8.0.12
  mac: 34:5A:60:E8:1F:0F
