led:
  ip: 10.8.1.21
  mac: BC:FC:E7:B4:84:9B
layout1:
  ip: 10.8.2.21
  mac: BC:FC:E7:B4:84:2D
layout2:
  ip: 10.8.2.22
  mac: BC:FC:E7:B4:84:2E
history:
  ip: 10.8.4.21
  mac: 10:7C:61:B5:6D:57
totalisator:
  ip: 10.8.5.21
  mac: 10:7C:61:B5:6E:24
phototable:
  ip: 10.8.6.21
  mac: BC:FC:E7:B4:84:8E
horses:
  ip: 10.8.7.21
  mac: BC:FC:E7:B4:83:B3
rysack1:
  ip: 10.8.8.21
  mac: BC:FC:E7:B4:82:BF
rysack2:
  ip: 10.8.8.22
  mac: BC:FC:E7:B4:82:C0
names:
  ip: 10.8.9.21
  mac: 10:7C:61:B5:6F:19
winners:
  ip: 10.8.10.21
  mac: 10:7C:61:B5:6D:FA
triplet1:
  ip: 10.8.11.21
  mac: BC:FC:E7:B4:84:CB
triplet2:
  ip: 10.8.11.22
  mac: BC:FC:E7:B4:84:CC
triplet3:
  ip: 10.8.11.23
  mac: BC:FC:E7:B4:84:CD
portreit:
  ip: 10.8.12.21
  mac: BC:FC:E7:B4:84:BE
horserider:
  ip: 10.8.13.21
  mac: BC:FC:E7:B4:83:B2
profession:
  ip: 10.8.14.21
  mac: BC:FC:E7:B4:83:30
budenniy:
  ip: 10.8.15.21
  mac: BC:FC:E7:B4:83:21
book:
  ip: 10.8.16.21
  mac: BC:FC:E7:B4:84:80
