- zone: relayMoscow
  equipment: controller_1
  ip: 10.8.1.141
- zone: relayStalin
  equipment: controller_1
  ip: 10.8.1.142
- zone: relayLenin
  equipment: controller_1
  ip: 10.8.1.143
- zone: relayKursk
  equipment: controller_1
  ip: 10.8.1.144
- zone: relayDnepro
  equipment: controller_1
  ip: 10.8.1.145
- zone: entrance
  equipment: pc_1
  ip: 10.8.2.11
- zone: entrance
  equipment: pj_1
  ip: 10.8.2.21
- zone: entrance
  equipment: pj_2
  ip: 10.8.2.22
- zone: entrance
  equipment: pj_3
  ip: 10.8.2.23
- zone: entrance
  equipment: pj_4
  ip: 10.8.2.24
- zone: germanPlans
  equipment: pc_1
  ip: 10.8.3.11
- zone: germanWarLed
  equipment: pc_1
  ip: 10.8.3.12
- zone: germanWarTouch
  equipment: pc_1
  ip: 10.8.3.13
- zone: statistics
  equipment: pc_1
  ip: 10.8.3.14
- zone: statistics
  equipment: pj_1
  ip: 10.8.3.21
- zone: germanTV
  equipment: pc_1
  ip: 10.8.4.11
- zone: familyLed
  equipment: pc_1
  ip: 10.8.5.11
- zone: familyMother
  equipment: pc_1
  ip: 10.8.5.16
- zone: familyFather
  equipment: pc_1
  ip: 10.8.5.15
- zone: familyDaugther
  equipment: pc_1
  ip: 10.8.5.14
- zone: familySon
  equipment: pc_1
  ip: 10.8.5.13
- zone: familyKids
  equipment: pc_1
  ip: 10.8.5.12
- zone: hijacking
  equipment: pc_1
  ip: 10.8.6.11
- zone: hijacking
  equipment: pj_1
  ip: 10.8.6.21
- zone: hijacking
  equipment: pj_2
  ip: 10.8.6.22
- zone: gazvagen
  equipment: pc_1
  ip: 10.8.6.12
- zone: gazvagen
  equipment: pj_1
  ip: 10.8.6.23
- zone: kids
  equipment: pc_1
  ip: 10.8.6.13
- zone: kids
  equipment: pj_1
  ip: 10.8.6.24
- zone: izba
  equipment: pc_1
  ip: 10.8.6.15
- zone: burnedLand
  equipment: pc_1
  ip: 10.8.6.14
- zone: burnedLand
  equipment: pj_1
  ip: 10.8.6.25
- zone: burnedTouch
  equipment: pc_1
  ip: 10.8.6.16
- zone: prisonMap
  equipment: pc_1
  ip: 10.8.6.17
- zone: prisonMap
  equipment: pj_1
  ip: 10.8.6.26
- zone: prisonBox
  equipment: pc_1
  ip: 10.8.6.18
- zone: nari
  equipment: pc_1
  ip: 10.8.6.19
- zone: birds
  equipment: pc_1
  ip: 10.8.7.11
- zone: birds
  equipment: pj_1
  ip: 10.8.7.21
- zone: boy
  equipment: pc_1
  ip: 10.8.7.12
- zone: boy
  equipment: pj_1
  ip: 10.8.7.22
- zone: boyTouch
  equipment: pc_1
  ip: 10.8.7.13
- zone: carriagePlatform
  equipment: pc_1
  ip: 10.8.9.11
- zone: carriagePlatform
  equipment: pj_1
  ip: 10.8.9.21
- zone: carriageCabinet
  equipment: pc_1
  ip: 10.8.9.15
- zone: carriageGirl
  equipment: pc_1
  ip: 10.8.9.14
- zone: carriageOfficer
  equipment: pc_1
  ip: 10.8.9.13
- zone: carriageOfficer
  equipment: pj_1
  ip: 10.8.9.22
- zone: carriageTranslucent
  equipment: pc_1
  ip: 10.8.9.12
- zone: keningMarket
  equipment: pc_1
  ip: 10.8.9.16
- zone: keningGirl
  equipment: pc_1
  ip: 10.8.9.17
- zone: keningGirl
  equipment: pj_1
  ip: 10.8.9.23
- zone: keningLetters
  equipment: pc_1
  ip: 10.8.9.18
- zone: flatDaugher
  equipment: pc_1
  ip: 10.8.10.11
- zone: flatWindow
  equipment: pc_1
  ip: 10.8.10.14
- zone: flatBoxLeft
  equipment: pc_1
  ip: 10.8.10.12
- zone: flatBoxRight
  equipment: pc_1
  ip: 10.8.10.13
- zone: leningrad
  equipment: pc_1
  ip: 10.8.10.15
- zone: leningrad
  equipment: pj_1
  ip: 10.8.10.21
- zone: leningrad
  equipment: pj_2
  ip: 10.8.10.22
- zone: culturePiano
  equipment: pc_1
  ip: 10.8.11.11
- zone: cultureKhabensky
  equipment: pc_1
  ip: 10.8.11.12
- zone: cultureKhabensky
  equipment: pj_1
  ip: 10.8.11.21
- zone: cultureTouch
  equipment: pc_1
  ip: 10.8.11.13
- zone: europe
  equipment: pc_1
  ip: 10.8.12.11
- zone: europe
  equipment: pj_1
  ip: 10.8.12.21
- zone: europe
  equipment: pj_2
  ip: 10.8.12.22
- zone: europeMap
  equipment: pc_1
  ip: 10.8.12.12
- zone: europeMap
  equipment: pj_1
  ip: 10.8.12.23
- zone: europeFather
  equipment: pc_1
  ip: 10.8.12.13
- zone: europeScale
  equipment: pc_1
  ip: 10.8.12.14
- zone: europeHolo
  equipment: pc_1
  ip: 10.8.12.15
- zone: europeCinema
  equipment: pc_1
  ip: 10.8.12.16
- zone: europeCinema
  equipment: pj_1
  ip: 10.8.12.24
- zone: japanHologram
  equipment: pc_1
  ip: 10.8.13.13
- zone: photosLeft
  equipment: pc_1
  ip: 10.8.13.15
- zone: photosLeft
  equipment: pj_1
  ip: 10.8.13.23
- zone: photosRight
  equipment: pc_1
  ip: 10.8.13.14
- zone: photosRight
  equipment: pj_1
  ip: 10.8.13.22
- zone: japanMap
  equipment: pc_1
  ip: 10.8.13.11
- zone: japanMap
  equipment: pj_1
  ip: 10.8.13.21
- zone: japanTranslucent
  equipment: pc_1
  ip: 10.8.13.12
- zone: japanSon
  equipment: pc_1
  ip: 10.8.13.16
- zone: nur
  equipment: pc_1
  ip: 10.8.14.11
- zone: nur
  equipment: pj_1
  ip: 10.8.14.21
- zone: nur
  equipment: pj_2
  ip: 10.8.14.22
- zone: court
  equipment: pc_1
  ip: 10.8.14.14
- zone: court
  equipment: pj_1
  ip: 10.8.14.23
- zone: nurTouchLeft
  equipment: pc_1
  ip: 10.8.14.12
- zone: nurTouchRight
  equipment: pc_1
  ip: 10.8.14.13
