zones:
  - id: led
    status:
      pc_1: 521
  - id: layout1
    status:
      pc_1: 521
  - id: layout2
    status:
      pc_1: 521
  - id: history
    status:
      pc_1: 521
  - id: totalisator
    status:
      pc_1: 521
  - id: phototable
    status:
      pc_1: 521
      pj_1: 520
  - id: horses
    status:
      pc_1: 521
  - id: rysack1
    status:
      pc_1: 521
  - id: rysack2
    status:
      pc_1: 521
  - id: names
    status:
      pc_1: 521
  - id: winners
    status:
      pc_1: 521
      pj_1: 520
  - id: triplet1
    status:
      pc_1: 521
  - id: triplet2
    status:
      pc_1: 521
  - id: triplet3
    status:
      pc_1: 521
  - id: portreit
    status:
      pc_1: 521
  - id: horserider
    status:
      pc_1: 521
      pj_1: 520
  - id: profession
    status:
      pc_1: 521
  - id: budenniy
    status:
      pc_1: 521
  - id: book
    status:
      pc_1: 521
      pj_1: 520
